// Adapted from @mariozechner/pi-coding-agent 0.70.2. Sync policy: cherry-pick. See ADR-0010.
/**
 * Session storage types — single source of truth for the on-disk JSONL shape.
 *
 * Schema is owned by Agentchan (ADR-0010). Wire format stays Pi v3-compatible
 * (ADR-0004). The 9-variant `SessionEntry` union and helper-touched fields are
 * preserved verbatim so behavior under `buildSessionContext` matches Pi v3.
 */

import type { AgentMessage } from "@mariozechner/pi-agent-core";
import type { ImageContent, TextContent } from "@mariozechner/pi-ai";

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
  type: "session";
  version?: number;
  id: string;
  timestamp: string;
  cwd: string;
  parentSession?: string;
}

export interface SessionEntryBase {
  type: string;
  id: string;
  parentId: string | null;
  timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
  type: "message";
  message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
  type: "thinking_level_change";
  thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
  type: "model_change";
  provider: string;
  modelId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
  type: "compaction";
  summary: string;
  firstKeptEntryId: string;
  tokensBefore: number;
  /** Extension-specific data (e.g., ArtifactIndex, version markers). */
  details?: T;
  /** True if generated by an extension, undefined/false if pi-generated (backward compatible). */
  fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
  type: "branch_summary";
  fromId: string;
  summary: string;
  /** Extension-specific data (not sent to LLM). */
  details?: T;
  /** True if generated by an extension, false if pi-generated. */
  fromHook?: boolean;
}

/**
 * Extension-only entry that does NOT participate in LLM context.
 * Use for persisting extension state across reloads.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
  type: "custom";
  customType: string;
  data?: T;
}

/** User-defined bookmark/marker on an entry. */
export interface LabelEntry extends SessionEntryBase {
  type: "label";
  targetId: string;
  label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
  type: "session_info";
  name?: string;
}

/**
 * Extension-injected message entry that DOES participate in LLM context.
 * Converted to a user message in `buildSessionContext`.
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
  type: "custom_message";
  customType: string;
  content: string | (TextContent | ImageContent)[];
  details?: T;
  display: boolean;
}

/** Tree node — has id/parentId. */
export type SessionEntry =
  | SessionMessageEntry
  | ThinkingLevelChangeEntry
  | ModelChangeEntry
  | CompactionEntry
  | BranchSummaryEntry
  | CustomEntry
  | CustomMessageEntry
  | LabelEntry
  | SessionInfoEntry;

/** Raw line in the JSONL file (header line + entry lines). */
export type FileEntry = SessionHeader | SessionEntry;

export interface SessionContext {
  messages: AgentMessage[];
  thinkingLevel: string;
  model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
  path: string;
  id: string;
  /** Working directory where the session was started. Empty string for old sessions. */
  cwd: string;
  /** User-defined display name from session_info entries. */
  name?: string;
  /** Path to the parent session (if this session was forked). */
  parentSessionPath?: string;
  created: Date;
  modified: Date;
  messageCount: number;
  firstMessage: string;
  allMessagesText: string;
}

export type SessionMode = "creative" | "meta";

/** Pi `SessionHeader` plus Agentchan's `mode` extension. */
export interface AgentchanSessionHeader extends SessionHeader {
  mode?: SessionMode;
}

/** SessionInfo augmented with Agentchan's `mode` and resolved title for list rendering. */
export interface AgentchanSessionInfo extends SessionInfo {
  mode: SessionMode;
  /** Title resolved from latest `session_info.name` or first user message. */
  title: string;
}
